appetite/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resource :session, only: [:new, :create, :destroy]

  get "user/inventories/search" => "inventories#search"

  resource :user do 
    resources :inventories, :recipes
  end

end

appetite/app/models/inventory.rb
class Inventory < ActiveRecord::Base
	has_and_belongs_to_many :recipes, dependent: :destroy,
		join_table: :inventories_recipes

	belongs_to :user
	
	# can't use this validation as diff users can have same ingredient
	# validates :ingredient, uniqueness: { message:  "Ingredient is already in your list" }
	validates :ingredient, presence: true

	validates :group, presence: true

	validates :avail, inclusion: { in: [true, false] }

	validates :user_id, presence: true

	default_scope {order(:ingredient => :ASC)}
end

appetite/app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_and_belongs_to_many :inventories, dependent: :destroy, 
		join_table: :inventories_recipes

	belongs_to :user

	validates :name, :api_id, :user_id, :ingredients, :instructions, presence: true

	validates :active, inclusion: { in: [true, false] }
	
	default_scope {order(:name => :ASC)}
end

appetite/app/models/user.rb
class User < ActiveRecord::Base
	has_many :inventories
	has_many :recipes
	has_secure_password
	validates_presence_of :name, :email
	validates :email, format: { with:  /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/, message: "Please check the format of your email." }, uniqueness:  {message: "Email already in system, please sign in."}

	def to_json(options = {})
		super(options.merge(:only => [:id, :name]))
	end
end

appetite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate

  private 
  def current_user 
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
  	redirect_to new_session_path unless current_user
  end

end

appetite/app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
	protect_from_forgery with: :null_session

	# searching for recipes
	def search
		# http header for api call
		options = {
			:headers => {
				"ACCEPT" => "application/json",
				"CONTENT-TYPE" => "application/json",
				"x-api-key" => "78861666c8ba" 
			}
		}

		# getting the search query
		checked = params[:ingredients].join("+").gsub(" ", "+")
		puts checked
		# making the call to weeatt for recipe
		response = HTTParty.get("http://www.weeatt.com/api/v1/recipes?qs=#{checked}&auth_token="+Rails.application.secrets.secret_password, options)
		# call to food2fork for image
		img_response = HTTParty.get("http://food2fork.com/api/search?key=61c9d5207dd3cfc98d3a7e81e9fada77&q=#{checked}")
		
		if response && img_response
			arr = []
			arr.push(response)
			arr.push(img_response)

			render json: arr
		else
			render status: 400, nothing: true
		end
	end


	# gets all of the users ingredients and any user recipes associated with that ingredient
	def index
		@user = User.find(session[:user_id])
		@inventories =  @user.inventories
		if @inventories
			render json: @inventories
		else
			render status: 400, nothing: true
		end
	end

	#gets the saved recipes associated with any one ingredient
	def show
		@inventory =  Inventory.find(params[:id])
		if @inventory
			render json: @inventory.to_json(:include => [:recipes])
		else
			render status: 400, nothing: true
		end
	end

	# create new ingredient, save it, let backbone rerender its view
	def create
		if Inventory.find_by({ingredient: params[:ingredient]}) 
			flash.now[:error] = "That item is already in your inventory."
			render status: 400, nothing: true
		else
			@inventory = Inventory.new(inventory_params)
			if @inventory.save
				render json: @inventory
			else
				render status: 400, nothing: true
			end
		end
	end

	# updates an ingredient; backbone's put route
	def update
		@inventory = Inventory.find(params[:id])
		if @inventory.update(inventory_params)
			render json: @inventory
		else
			render status: 400, nothing: true
		end
	end

	# deletes inventory and all associatons
	def destroy
		@inventory = Inventory.find(params[:id])
		if @inventory.destroy
			render json: {}
		else
			render status: 400, nothing: true
		end
	end

	# private params for form when saving and updating
	private
	def inventory_params
		params.require(:inventory).permit(:ingredient, :group, :avail, :user_id, )
	end
end

appetite/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	protect_from_forgery with: :null_session

	# all recipes corresponding to one user
	def index
		@recipes = Recipe.where(user_id: session[:user_id])
		if @recipes
			render json: @recipes.to_json(:include => [:inventories])
		else
			flash[:error] = "You haven't saved any recipes yet! Search now :)"
			render status: 400, nothing: true
		end
	end

	# showing as saved recipe with corresponding inventory
	def show
		@recipe = Recipe.find(params[:id])
		if @recipe 
			render json: @recipe.to_json(:include => [:inventories])
		else
			render status: 400, nothing: true
		end
	end

	# saving a recipe to the db
	def create
		if Recipe.find_by({api_id: params[:api_id]})
			flash[:error] = "Recipe '#{params[:name]}' already exists in your saved recipes."
		else
			@recipe = Recipe.new(recipe_params)
			if @recipe.save
				ids = params[:inventories].split(",")
				for index in 0...ids.length
					@recipe.inventories << Inventory.where({id: ids[index].to_i})
				end

				render json: @recipe
			else
				render status: 400, nothing: true
			end
		end
	end

	# updating a recipe 
	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update(recipe_params)
			render json: @recipe
		else
			render status: 400, nothing: true
		end
	end

	# deleting an unwanted recipe
	def destroy
		@recipe = Recipe.find(params[:id])
		if @recipe.destroy
			render json: {}
		else
			render status: 400, nothing: true
		end
	end

	# private recipe params
	private
	def recipe_params
		params.require(:recipe).permit(:name, :api_id, :instructions, :user_id, :active, :ingredients)
	end

end

appetite/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	protect_from_forgery with: :null_session
	before_action :authenticate, only: [:destroy]

	# new session login
	def new
		if session[:user_id] 
			redirect_to user_path
		end
	end

	# starts a new session
	def create
		user = User.find_by({email: params[:email]})
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			session[:name] = user.name
			redirect_to user_path 
		else 
			@email = params[:email]
			flash.now[:error] = "Unknown email/password"
			render :new
		end
	end

	# destroy session on logout
	def destroy
		reset_session 
		redirect_to new_session_path
	end

end

appetite/app/controllers/users_controller.rb
class UsersController < ApplicationController
	protect_from_forgery with: :null_session
	before_action :authenticate, except: [:create]

	# user show page
	def show
		# only if user logged-in
		@user = User.find(session[:user_id])

		# sending either html or json to user show page
		respond_to do |format|
			format.html { render :show }
			# sends monstrous json with user and all associated inventories and recipes and their associations
			format.json { render json: @user.to_json(include: {inventories: { include: { recipes: {only: [:id]}}}, recipes: {include: {inventories: {only: [:id]}}}})}
		end
	end

	# creating a new user
	def create
		@user = User.new(name: params[:name], email: params[:email], password: params[:password])
		# if new user passes validation
		if @user.save
			session[:user_id] =  @user.id
			session[:name] = @user.name
			flash[:success] = "Welcome #{@user.name}! Start off by filling out your inventory."
			# is it possible to redirect to a backbone page - how to use site
			redirect_to user_path

		# if user failed validation
		else 
			flash.now[:error] = "Please check your inputs!"
			redirect_to new_session_path
		end
	end

end

appetite/app/helpers/application_helper.rb
module ApplicationHelper
end

appetite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<%= favicon_link_tag 'favicon.png' %>
 <meta name="viewport" content="width=device-width, initial-scale=1">
<head>
  <title>Frigeratr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    _.templateSettings = {
     evaluate    : /\{\{([\s\S]+?)\}\}/g,
     interpolate : /\{\{=([\s\S]+?)\}\}/g,
     escape      : /\{\{-([\s\S]+?)\}\}/g
   };
 </script>
</head>
<header class="header"> <div id="title_bar">    <div id="logo"></div>  

  <div id= "menu_bar">

    <div class="menu_items">
    <% if @user %>
     <li id="menu_act_recipes"> <a class="nav_link" href="#"> Active Recipes </li> 
      <li id="menu_recipes"> <a class="nav_link" href="#recipes"> Saved Recipes </li> 
      <li id="menu_inv"> <a class="nav_link" href="#inventory"> Inventory </li> 
    <%= link_to "Logout", session_path, method: :delete, id: "menu_logout", class: "nav_link" %></li>
    <% end %>
    </div>
    </div>
  </div>


  </header>
  <% if @user %>
  <center><h2 id="greeting"> Hello, <%= @user.name %>. Let's get cooking! </h2> </center>
  <% end %>
  <body>
    <% if flash %>
    <% flash.each do |name, message| %>
    <div class="flash-<%= name %>"><%= message %></div>
    <% end %>
    <% end %>

    <%= yield %>

  </body>
  </html>

appetite/app/views/users/show.html.erb
<script>
	var thisUserId = <%= session[:user_id] %>
</script>
<!--picture area-->
<div id="sidebar"></div>

 <!-- template to add a new inventory item -->
<script type="text/template" id="create-inventory">
<div id="inventory-form">
  <h2>Add An Ingredient</h2>
  <%= text_field_tag :ingredient, nil, placeholder: "ingredient name" %>
  <%= select_tag :group, options_for_select([["Protein", "protein"],["Produce", "produce"],["Dairy", "dairy"],["Grain", "grain"]]) %>
  <%= button_tag "ADD", id: "add-inventory" %>
</div>
</script>

<!-- this is where view content will be appended -->
<div id="content"></div>

<script type="text/javascript">
	// getting rid of weird symbols in returned text
	// first changes the string to hexcode
	String.prototype.toUnicode = function(){
	    var result = "";
	    for(var i = 0; i < this.length; i++){
	        result += "\\u" + ("000" + this[i].charCodeAt(0).toString(16)).substr(-4);
	    }
	    return result;
	};
	// changed the hexcode back to human language
	function hex2a(hex) {
	    var str = '';
	    for (var i = 0; i < hex.length; i += 2) str += String.fromCharCode(parseInt(hex.substr(i, 2), 16));
	    return str;
	}
	// calling above functions, ridding of more weird symbols and replacing new line breaks
	String.prototype.nl2br = function() {
		var hex_coded = this.replace(/\r\n/g, "<<<").toUnicode();
    	return hex2a(hex_coded).replace(/[^\w\-\\\s\/\\.#'"%()<]/g, "").replace(/<<</g, "<br />");
	};
</script>

<!-- template for user's currently active recipe(s) -->
<script type="text/template" id="active-recipe"> 
	<div id="active-recipe-div">
		<img class="recipe-pic" src="">
		<h2 class="recipe-title"> {{=  recipe.name }}</h2>
		<p class="recipe-ingredients">{{= recipe.ingredients.nl2br() }}</p>



{{ if (recipe.active == true) { }} <button id={{=recipe.id}} class="dectivate-butt" style="background-color:rgb(254,215,53)"> Deactivate </button> {{ } else { }} <button id={{=recipe.id}} class="activate-butt" style="background-color:rgb(154,153,153)"> Inactive </button> 
		{{ }; }}

		<button class="delete-butt">Delete</button>

		<div id="update-ingredient">
		<h3>Ingredients Linked to Recipe: </h3> 
		{{ recipe.inventories.forEach(function(inventory){ }}
			<p>{{= inventory.ingredient }}</p>
		<button style="{{ if (inventory.avail == true){ }} background-color: green {{ } else { }} background-color: red {{ } }}" class="avail-butt" id="{{= inventory.id }}">Used?</button>
		{{ }) }}
	</div>
</script>

<!-- template for recipe search results -->
<script type="text/template" id="recipe-result">
	<div id="recipe-result-div">
		<h2 class="recipe-name">{{= recipe.name }}</h2>
		<p class="recipe-ingredients">{{= recipe.ingredients.nl2br() }}</p>
		<button class="read-more" id="instructions-{{= recipe.id }}">See Cooking Instructions</button>
		<p style="display: none" class="recipe-instructions">{{= recipe.instructions }}</p>
		<input type="hidden" class="user_id" value="{{= recipe.user_id }}">
		<input type="hidden" class="inventories_ids" value="{{= recipe.inventories_ids }}">
		<button class="save-button" id="{{= recipe.id }}">Save</button>
	</div>	 
</script>

<!-- template for all of user's saved recipes -->
<script type="text/template" id="each-recipe">
	<div id="all-recipes-div">
		<h2><a href="#recipe/{{= recipe.id }}" class="recipe-title"> {{= recipe.name }}</a></h2>
		<p class="recipe-ingredients">{{= recipe.ingredients.nl2br() }}</p>

		{{ if (recipe.active == true) { }} <button id={{=recipe.id}} class="activate-butt" style="background-color:rgb(254,215,53)"> Active </button> {{ } else { }} <button id={{=recipe.id}} class="activate-butt" style="background-color:rgb(154,153,153)"> Inactive </button> 
		{{ }; }}

		<button class="delete-butt">Delete</button>
	</div>
</script>

<!--shows clicked recipe-->
<script type="text/template" id="show-recipe">
	<div id="all-recipes-div">
		<h2>{{= recipe.name }}</a></h2>	
		<p class="recipe-ingredients">{{= recipe.ingredients.nl2br() }}</p>
		<p class="recipe-instructions">{{= recipe.instructions }}</p>
		<button class="activate-butt" style="{{ if (recipe.active == true){ }} background-color: green {{ } else { }} background-color: red {{ } }}">Activate</button>
		<button class="delete-butt">Delete</button>
		<h2> From your inventory: </h2>
			{{ recipe.inventories.forEach(function(inventory) { }}
				<div class="invent-item"> 
				<h3 class= "invent-name">{{= inventory.ingredient }}</h3>
				<button id="{{= inventory.id }}" class="avail-butt" style="{{ if (inventory.avail == true){ }} background-color: rgb(254,215,53) {{ } else { }} background-color: rgb(154,153,153) {{ } }}"> Available</button>

			{{ }); }}
	</div>
</script>

<!-- shows clicked on inventory item -->
<script type="text/template" id="show-inventory">
	<h1>{{= inventory.ingredient }}</h1>
	<button id="avail-butt" style="{{ if (inventory.avail == true){ }} background-color: green {{ } else { }} background-color: red {{ } }}">{{ if (inventory.avail == true){ }} Available {{ } else { }} Unavailable {{ } }}</button>
		<button class="delete-butt">Delete</button>
		<h2> Linked to these recipes: </h2>
		<div class="recipes-itemized"> 
			{{ inventory.recipes.forEach(function(recipe) { }}
				<h3 class="recipe-name">{{= recipe.name }}</h3>
				<button id="{{= recipe.id }}" class="active-butt" style="{{ if (recipe.active == true){ }} background-color: green {{ } else { }} background-color: red {{ } }}">Activate Recipe</button>
			{{ }); }}
		</div>
</script>

<!-- template for each inventory item on the inventory index page -->
<script type="text/template" id="each-inventory">
<div id="all-inventory-div">
	<a href="#inventory/{{=inventory.id}}" class="inventory-title">{{=inventory.ingredient}}</a>
	<ul class="ing-butts">
	
	{{ if (inventory.avail === true){ }} 
	<button id = "{{= inventory.id }}" class="avail-butt" style="background-color:rgb(254,215,53)"> Available</button>{{ } else { }} <button id = "{{= inventory.id }}" class="avail-butt" style="background-color:rgb(154,153,153)"> Unavailable </button> {{ }; }}

	<button class="delete-butt">Delete</button>
	<input type="hidden" id="hidden-userId" value="{{= inventory.user_id }}">
	<input type="checkbox" name="ingredients" id="{{= inventory.id }}" class="checked-ingredient" value="{{= inventory.ingredient }}"></ul>
</script>